Repository apache/openwhisk-cli, pull requests merged in 2018-03, with the labels that each got.

#238 Addition HTTP Headers
  build.gradle
  commands/commands.go
Labels: review

#248 Fix test to not compare namespace to subject
  tests/src/test/scala/system/basic/WskBasicTests.scala
Labels: review, tests

#247 Fix intermittent test failure
  tests/src/test/scala/system/basic/WskBasicTests.scala
Labels: review, testing
